version: '3'
services:

  imaginethis-db:
    build: ./ImagineThisDatabase
    container_name: imaginethis-db
    volumes:
      - imaginethis-db-vol:/var/lib/postgresql/data
    ports:
      - 5432

  imaginethis-backend:
    build: ./ImagineThisServer
    container_name: imaginethis-backend
    environment:
      - IMAGINE_THIS_DB_HOST=postgresql://imaginethis-db
      - IMAGINE_THIS_DB_PORT=5432
      - IMAGINE_THIS_DB_NAME=
      - IMAGINE_THIS_USERNAME=
      - IMAGINE_THIS_PASSWORD=
      - CORS_ORIGIN=
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8080:8080
    links:
      - imaginethis-db

  imaginethis-frontend:
    build: 
      context: ./ImagineThisWeb
      # setting up build time environment variable
      args: 
        - REACT_APP_BACKEND_ADDRESS=
        - REACT_APP_DOMAIN=
    container_name: imaginethis-frontend
    environment:
      - NODE_ENV=production
    ports:
      - 80:80
    links:
      - imaginethis-backend

volumes:
  imaginethis-db-vol:
