version: '3'
services:

  imaginethis-db:
    build: 
      context: ./ImagineThisDatabase
      args:
        - POSTGRES_DB=
        - POSTGRES_USER=
        - POSTGRES_PASSWORD=
    container_name: imaginethis-db
    volumes:
      - imaginethis-db-vol:/var/lib/postgresql/data
    ports:
      - 5432

  imaginethis-backend:
    build: ./ImagineThisServer
    container_name: imaginethis-backend
    environment:
      - IMAGINE_THIS_DB_HOST=postgresql://imaginethis-db
      - IMAGINE_THIS_DB_PORT=5432
      # The following DB configurations should be the same as the args from imaginethis-db
      - IMAGINE_THIS_DB_NAME=
      - IMAGINE_THIS_USERNAME=
      - IMAGINE_THIS_PASSWORD=
      - CORS_ORIGIN=
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8080:8080
    links:
      - imaginethis-db

  imaginethis-frontend:
    build: 
      context: ./ImagineThisWeb
      # setting up build time environment variable
      args: 
        - REACT_APP_BACKEND_ADDRESS=
        - REACT_APP_DOMAIN=
    container_name: imaginethis-frontend
    environment:
      - NODE_ENV=production
    ports:
      - 80:80
    links:
      - imaginethis-backend
  
  # We want to build the "expo" container as it will be used for asynchronous publishing jobs
  imaginethis-expo: 
    build:
      context: ./ImagineThisExpo
      args:
        - EXPO_TOKEN=
        - DB_HOST=
        - DB_PORT=
        - DB_NAME=
        - DB_USERNAME=
        - DB_PASSWORD=

volumes:
  imaginethis-db-vol:
